Recheck host to avoid spurious error on cli -S with missing-host
NoMethodError: undefined method `[]' for nil:NilClass
  /home/david/src/syncwrap/lib/syncwrap.rb:291:in `ssh_host_name'

should instead be:

RuntimeError: Host foo-host not found in sync file

given '-S foo-host'.