RHEL.dist_if_not_installed? needs to count installed package lines
`yum list installed` will return 0 (true) if even a single package of
the set specified is installed. See below example. Thus we need to
count the package lines after the header.

  % yum list -C -q installed foobar; echo $?
  Error: No matching Packages to list
  1

  % yum list -C -q installed make foobar; echo $?
  Installed Packages
  make.x86_64  1:3.82-21.el7  @anaconda
  0

 Note Error... in first example is to STDERR.